language: vi

pipeline: # quá trình huấn luyện bot hiểu đc nlu
  - name: VietnameseTokenizer
  - name: "CRFEntityExtractor"
    "BILOU_flag": True
    "features": [
      ["low", "title", "upper"],
      [
        "bias",
        "low",
        "prefix5",
        "prefix2",
        "suffix5",
        "suffix3",
        "suffix2",
        "upper",
        "title",
        "digit",
        "pattern",
      ],
      ["low", "title", "upper"],
    ]
  - name: CountVectorsFeaturizer # trích xuất đặc trưng
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: RegexEntityExtractor
    # text will be processed with case insensitive as default
    case_sensitive: False
    # use lookup tables to extract entities
    use_lookup_tables: True
    # use regexes to extract entities
    use_regexes: True
  - name: rasa_nlu_examples.featurizers.dense.BytePairFeaturizer
    lang: vi
    vs: 1000
    dim: 25
  - name: DIETClassifier # phân loại ý định người dùng và trích xuất thực thể
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper # map những thực thể đồng nghĩa lại
  - name: ResponseSelector # lựa chọn câu hỏi trả về
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.4 # tất cả các dự đoán khác nằm dưới ngưỡng 0.4

# Configuration for Rasa Core.
policies: # đào tạo file stories
  - name: MemoizationPolicy # lưu trữ lịch sử hội thoại đoán kịch bản
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
  - name: RulePolicy
    core_fallback_threshold: 0.3 # hành động sẽ được áp dụng nếu k có dự đoán nào trên 0.3
    core_fallback_action_name: "utter_default"
